/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthenticationImport } from './routes/_authentication'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexImport } from './routes/_authenticated/index'
import { Route as AuthenticationLogInImport } from './routes/_authentication/log-in'
import { Route as AuthenticationForgetPasswordImport } from './routes/_authentication/forget-password'
import { Route as AuthenticatedDailyLessonsImport } from './routes/_authenticated/daily-lessons'

// Create/Update Routes

const AuthenticationRoute = AuthenticationImport.update({
  id: '/_authentication',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedIndexRoute = AuthenticatedIndexImport.update({
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticationLogInRoute = AuthenticationLogInImport.update({
  path: '/log-in',
  getParentRoute: () => AuthenticationRoute,
} as any)

const AuthenticationForgetPasswordRoute =
  AuthenticationForgetPasswordImport.update({
    path: '/forget-password',
    getParentRoute: () => AuthenticationRoute,
  } as any)

const AuthenticatedDailyLessonsRoute = AuthenticatedDailyLessonsImport.update({
  path: '/daily-lessons',
  getParentRoute: () => AuthenticatedRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/_authentication': {
      id: '/_authentication'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticationImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/daily-lessons': {
      id: '/_authenticated/daily-lessons'
      path: '/daily-lessons'
      fullPath: '/daily-lessons'
      preLoaderRoute: typeof AuthenticatedDailyLessonsImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authentication/forget-password': {
      id: '/_authentication/forget-password'
      path: '/forget-password'
      fullPath: '/forget-password'
      preLoaderRoute: typeof AuthenticationForgetPasswordImport
      parentRoute: typeof AuthenticationImport
    }
    '/_authentication/log-in': {
      id: '/_authentication/log-in'
      path: '/log-in'
      fullPath: '/log-in'
      preLoaderRoute: typeof AuthenticationLogInImport
      parentRoute: typeof AuthenticationImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexImport
      parentRoute: typeof AuthenticatedImport
    }
  }
}

// Create and export the route tree

interface AuthenticatedRouteChildren {
  AuthenticatedDailyLessonsRoute: typeof AuthenticatedDailyLessonsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDailyLessonsRoute: AuthenticatedDailyLessonsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface AuthenticationRouteChildren {
  AuthenticationForgetPasswordRoute: typeof AuthenticationForgetPasswordRoute
  AuthenticationLogInRoute: typeof AuthenticationLogInRoute
}

const AuthenticationRouteChildren: AuthenticationRouteChildren = {
  AuthenticationForgetPasswordRoute: AuthenticationForgetPasswordRoute,
  AuthenticationLogInRoute: AuthenticationLogInRoute,
}

const AuthenticationRouteWithChildren = AuthenticationRoute._addFileChildren(
  AuthenticationRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof AuthenticationRouteWithChildren
  '/daily-lessons': typeof AuthenticatedDailyLessonsRoute
  '/forget-password': typeof AuthenticationForgetPasswordRoute
  '/log-in': typeof AuthenticationLogInRoute
  '/': typeof AuthenticatedIndexRoute
}

export interface FileRoutesByTo {
  '': typeof AuthenticationRouteWithChildren
  '/daily-lessons': typeof AuthenticatedDailyLessonsRoute
  '/forget-password': typeof AuthenticationForgetPasswordRoute
  '/log-in': typeof AuthenticationLogInRoute
  '/': typeof AuthenticatedIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authentication': typeof AuthenticationRouteWithChildren
  '/_authenticated/daily-lessons': typeof AuthenticatedDailyLessonsRoute
  '/_authentication/forget-password': typeof AuthenticationForgetPasswordRoute
  '/_authentication/log-in': typeof AuthenticationLogInRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '' | '/daily-lessons' | '/forget-password' | '/log-in' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '' | '/daily-lessons' | '/forget-password' | '/log-in' | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authentication'
    | '/_authenticated/daily-lessons'
    | '/_authentication/forget-password'
    | '/_authentication/log-in'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthenticationRoute: typeof AuthenticationRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthenticationRoute: AuthenticationRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_authenticated",
        "/_authentication"
      ]
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/daily-lessons",
        "/_authenticated/"
      ]
    },
    "/_authentication": {
      "filePath": "_authentication.tsx",
      "children": [
        "/_authentication/forget-password",
        "/_authentication/log-in"
      ]
    },
    "/_authenticated/daily-lessons": {
      "filePath": "_authenticated/daily-lessons.tsx",
      "parent": "/_authenticated"
    },
    "/_authentication/forget-password": {
      "filePath": "_authentication/forget-password.tsx",
      "parent": "/_authentication"
    },
    "/_authentication/log-in": {
      "filePath": "_authentication/log-in.tsx",
      "parent": "/_authentication"
    },
    "/_authenticated/": {
      "filePath": "_authenticated/index.tsx",
      "parent": "/_authenticated"
    }
  }
}
ROUTE_MANIFEST_END */
