name: Quality Check
on:
  pull_request:
    branches: ["develop"]
jobs:
  build-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-dependencies
      - run: pnpm build